version: '2.3'

services:
  pavlov:
    image: InterfaceGUI/pavlov-server:latest
    volumes:
    - ./Game.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini
    - ./RconSettings.txt:/home/steam/pavlovserver/Pavlov/Saved/Config/RconSettings.txt
    environment:
    - PORT=7777
    ports:
    - 7777:7777/udp
    - 8177:8177/udp
    - 7777:7777/tcp
    - 8177:8177/tcp
    - 9100:9100/tcp
